version: '3.7'

services:

  adminer:
    image: adminer:4.7
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`$ADMINER_DOMAIN`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=myresolver"
      - "traefik.http.routers.adminer.tls.domains[0].main=$ADMINER_DOMAIN"
      - "traefik.http.routers.adminer.middlewares=adminer-basicauth"
      - "traefik.http.middlewares.adminer-basicauth.basicauth.users=$ADMINER_BASIC_AUTH"
      - "traefik.http.middlewares.adminer-basicauth.basicauth.removeheader=true"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      internal-brige:
        aliases:
          - adminer

networks:
  internal-brige:
    name: internal-brige
