version: "3.7"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: "dozzle"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`$DOZZLE_BASIC_AUTH`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.tls.domains[0].main=$DOZZLE_BASIC_AUTH"
      - "traefik.http.routers.dozzle.middlewares=dozzle-basicauth,dozzle-compress"
      - "traefik.http.middlewares.dozzle-compress.compress=true"
      - "traefik.http.middlewares.dozzle-basicauth.basicauth.users=$DOZZLE_BASIC_AUTH"
      - "traefik.http.middlewares.dozzle-basicauth.basicauth.removeheader=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      internal-brige:
        aliases:
          - dozzle

networks:
  internal-brige:
    name: internal-brige
